# Generated by Django 4.2.20 on 2025-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactform_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Examination'), ('event', 'School Event'), ('activity', 'Activity'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_important', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
